class EidosConstants {
  // 에이도스 카드 타입 매핑
  static const Map<String, String> EIDOS_TYPE_MAPPING = {
    'The Wind of Change of Free Innovator': 'Innovator',
    'The Wealth Organizer of Creative Affluent': 'Affluent',
    'The Visionary Realizer of Great Manifestor': 'Manifestor',
    'The Visionary Entrepreneur of Golden Pioneer': 'Pioneer',
    'The Unstoppable Pioneer of Indomitable Explorer': 'Explorer',
    'The True Unifier of Relationship Artisan': 'Unifier',
    'The Transformative Catalyst of Inner Alchemist': 'Alchemist',
    'The Strategic Adaptor of Flexible Strategist': 'Strategist',
    'The Soulful Nurturer of Compassionate Healer': 'Healer',
    'The Solitary Sage of Abyss Explorer': 'Sage',
    'The Social Network Builder of Relationship Artisan': 'Networker',
    'The Social Influencer of Golden Pioneer': 'Influencer',
    'The Shadow Conqueror of Inner Alchemist': 'Conqueror',
    'The Serene Scholar of Wise Guide': 'Scholar',
    'The Serene Oracle of Spiritual Enlightener': 'Oracle',
    'The Sage of Suffering of Inner Alchemist': 'Sage',
    'The Resilient Verdant Architect of Green Mercenary': 'Architect',
    'The Resilient Artisan of Strong-willed Lighthouse': 'Artisan',
    'The Principled Administrator of Resolute Designer': 'Administrator',
    'The Pragmatic Magnate of Golden Pioneer': 'Magnate',
    'The Pragmatic Builder of Resolute Designer': 'Builder',
    'The Passionate Seeker of Radiant Creator': 'Creator',
    'The Mediator of Peace of Compassionate Healer': 'Mediator',
    'The Luminous Servant of Compassionate Healer': 'Servant',
    'The Light Bearer of Spiritual Enlightener': 'Light Bearer',
  };

  // 에이도스 카드 설명
  static const Map<String, String> EIDOS_DESCRIPTIONS = {
    'Innovator': 'A free spirit who brings change and innovation to the world.',
    'Affluent': 'A creative organizer who manifests wealth and abundance.',
    'Manifestor': 'A visionary who turns dreams into reality.',
    'Pioneer': 'An entrepreneur who blazes new trails.',
    'Explorer': 'An unstoppable force of discovery and adventure.',
    'Unifier': 'A master of relationships and harmony.',
    'Alchemist': 'A transformative catalyst of inner change.',
    'Strategist': 'A flexible adapter who navigates life\'s challenges.',
    'Healer': 'A compassionate nurturer of others.',
    'Sage': 'A solitary explorer of deep wisdom.',
    'Networker': 'A builder of meaningful connections.',
    'Influencer': 'A social catalyst for positive change.',
    'Conqueror': 'A master of inner transformation.',
    'Scholar': 'A wise guide through knowledge.',
    'Oracle': 'A spiritual enlightener of higher truths.',
    'Architect': 'A resilient creator of sustainable systems.',
    'Artisan': 'A strong-willed beacon of creativity.',
    'Administrator': 'A principled designer of order.',
    'Magnate': 'A pragmatic leader of enterprise.',
    'Builder': 'A practical creator of lasting structures.',
    'Creator': 'A passionate seeker of artistic expression.',
    'Mediator': 'A bringer of peace and harmony.',
    'Servant': 'A luminous helper of others.',
    'Light Bearer': 'A spiritual guide of enlightenment.',
  };

  // 에이도스 카드 키워드
  static const Map<String, List<String>> EIDOS_KEYWORDS = {
    'Innovator': ['Change', 'Freedom', 'Innovation', 'Adaptability'],
    'Affluent': ['Wealth', 'Creativity', 'Organization', 'Abundance'],
    'Manifestor': ['Vision', 'Realization', 'Power', 'Creation'],
    'Pioneer': ['Leadership', 'Innovation', 'Courage', 'Discovery'],
    'Explorer': ['Adventure', 'Independence', 'Curiosity', 'Resilience'],
    'Unifier': ['Harmony', 'Relationships', 'Connection', 'Balance'],
    'Alchemist': ['Transformation', 'Inner Work', 'Change', 'Wisdom'],
    'Strategist': ['Adaptability', 'Planning', 'Flexibility', 'Intelligence'],
    'Healer': ['Compassion', 'Nurturing', 'Care', 'Empathy'],
    'Sage': ['Wisdom', 'Solitude', 'Depth', 'Understanding'],
    'Networker': ['Connection', 'Community', 'Relationships', 'Support'],
    'Influencer': ['Impact', 'Leadership', 'Inspiration', 'Change'],
    'Conqueror': ['Transformation', 'Strength', 'Overcoming', 'Power'],
    'Scholar': ['Knowledge', 'Wisdom', 'Learning', 'Teaching'],
    'Oracle': ['Spirituality', 'Guidance', 'Insight', 'Enlightenment'],
    'Architect': ['Creation', 'Structure', 'Sustainability', 'Design'],
    'Artisan': ['Creativity', 'Strength', 'Expression', 'Craft'],
    'Administrator': ['Order', 'Structure', 'Leadership', 'Efficiency'],
    'Magnate': ['Success', 'Leadership', 'Wealth', 'Power'],
    'Builder': ['Creation', 'Structure', 'Practicality', 'Durability'],
    'Creator': ['Artistry', 'Passion', 'Expression', 'Innovation'],
    'Mediator': ['Peace', 'Harmony', 'Balance', 'Understanding'],
    'Servant': ['Service', 'Light', 'Help', 'Support'],
    'Light Bearer': ['Guidance', 'Enlightenment', 'Wisdom', 'Spirituality'],
  };
}
