// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHY8Q3dhX9_bEmIke6I6afoMheErMw3bs',
    appId: '1:1024812024678:web:41be043952517acb8abea7',
    messagingSenderId: '1024812024678',
    projectId: 'innerfive',
    authDomain: 'innerfive.firebaseapp.com',
    storageBucket: 'innerfive.firebasestorage.app',
    measurementId: 'G-XS03TWK8LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKBBNLV-LoatdlANot-0b_Z44Hm4U7N4',
    appId: '1:1024812024678:android:72bcbac71206656a8abea7',
    messagingSenderId: '1024812024678',
    projectId: 'innerfive',
    storageBucket: 'innerfive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmNjlOs40wjuaYAxRTkFP1jpIiHIHHQRI',
    appId: '1:1024812024678:ios:bb8353db2bff919a8abea7',
    messagingSenderId: '1024812024678',
    projectId: 'innerfive',
    storageBucket: 'innerfive.firebasestorage.app',
    iosClientId: '1024812024678-fkq9o43g9pkjhv3fqushljio0k1b517h.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerfive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmNjlOs40wjuaYAxRTkFP1jpIiHIHHQRI',
    appId: '1:1024812024678:ios:bb8353db2bff919a8abea7',
    messagingSenderId: '1024812024678',
    projectId: 'innerfive',
    storageBucket: 'innerfive.firebasestorage.app',
    iosClientId: '1024812024678-fkq9o43g9pkjhv3fqushljio0k1b517h.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerfive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHY8Q3dhX9_bEmIke6I6afoMheErMw3bs',
    appId: '1:1024812024678:web:e721af403ced53778abea7',
    messagingSenderId: '1024812024678',
    projectId: 'innerfive',
    authDomain: 'innerfive.firebaseapp.com',
    storageBucket: 'innerfive.firebasestorage.app',
    measurementId: 'G-JD7K1LJNYE',
  );

}