class GanzhiUtils {
  static String getGanzhiMeaning(String ganzhi) {
    return _ganzhiMeanings[ganzhi] ?? 'Energy of the day';
  }

  static const Map<String, String> _ganzhiMeanings = {
    '甲子': 'Wood Rat: Cleverness & New Beginnings',
    '乙丑': 'Wood Ox: Steady & Patient Progress',
    '丙寅': 'Fire Tiger: Passion & Bold Action',
    '丁卯': 'Fire Rabbit: Inner Warmth & Creativity',
    '戊辰': 'Earth Dragon: Grand Vision & Stability',
    '己巳': 'Earth Snake: Calculated Wisdom & Insight',
    '庚午': 'Metal Horse: Decisive Action & Leadership',
    '辛未': 'Metal Goat: Artistic Sensitivity & Grace',
    '壬申': 'Water Monkey: Adaptable Intelligence & Flow',
    '癸酉': 'Water Rooster: Eloquence & Meticulous Planning',
    '甲戌': 'Wood Dog: Loyalty & Protective Instincts',
    '乙亥': 'Wood Pig: Generosity & Harmonious Living',
    '丙子': 'Fire Rat: Energetic Ideas & Social Charm',
    '丁丑': 'Fire Ox: Persistent Drive & Inner Strength',
    '戊寅': 'Earth Tiger: Ambitious Leadership & Grounded Power',
    '己卯': 'Earth Rabbit: Gentle Nurturing & Practicality',
    '庚辰': 'Metal Dragon: Strong Will & Transformative Power',
    '辛巳': 'Metal Snake: Sharp Intellect & Refined Strategy',
    '壬午': 'Water Horse: Emotional Awareness & Fluid Motion',
    '癸未': 'Water Goat: Empathetic Intuition & Gentle Flow',
    '甲申': 'Wood Monkey: Innovative Ideas & Resourcefulness',
    '乙酉': 'Wood Rooster: Systematic Growth & Detailed Work',
    '丙戌': 'Fire Dog: Fiery Loyalty & Moral Conviction',
    '丁亥': 'Fire Pig: Passionate Connection & Emotional Depth',
    '戊子': 'Earth Rat: Resourceful Planning & Groundedness',
    '己丑': 'Earth Ox: Methodical & Unwavering Dedication',
    '庚寅': 'Metal Tiger: Bold Justice & Powerful Resolve',
    '辛卯': 'Metal Rabbit: Refined Aesthetics & Delicate Skill',
    '壬辰': 'Water Dragon: Dynamic Flow & Deep Wisdom',
    '癸巳': 'Water Snake: Deep Intuition & Strategic Flow',
    '甲午': 'Wood Horse: Vigorous Growth & Expansive Energy',
    '乙未': 'Wood Goat: Compassionate Growth & Artistic Harmony',
    '丙申': 'Fire Monkey: Brilliant Innovation & Playful Energy',
    '丁酉': 'Fire Rooster: Illuminating Insight & Precision',
    '戊戌': 'Earth Dog: Foundational Loyalty & Trustworthiness',
    '己亥': 'Earth Pig: Grounded Generosity & Social Harmony',
    '庚子': 'Metal Rat: Clear Principles & Sharp Intellect',
    '辛丑': 'Metal Ox: Resilient Strength & Valued Traditions',
    '壬寅': 'Water Tiger: Instinctive Courage & Deep Currents',
    '癸卯': 'Water Rabbit: Gentle Intuition & Nurturing Flow',
    '甲辰': 'Wood Dragon: Pioneering Growth & Bold Vision',
    '乙巳': 'Wood Snake: Flexible Growth & Strategic Wisdom',
    '丙午': 'Fire Horse: Peak Passion & Radiant Charisma',
    '丁未': 'Fire Goat: Artistic Flame & Quiet Strength',
    '戊申': 'Earth Monkey: Practical Ingenuity & Stability',
    '己酉': 'Earth Rooster: Organized & Productive Diligence',
    '庚戌': 'Metal Dog: Righteous Duty & Strong Principles',
    '辛亥': 'Metal Pig: Refined Taste & Enjoyment of Life',
    '壬子': 'Water Rat: Deep Social Connections & Intelligence',
    '癸丑': 'Water Ox: Navigating Depths with Patience',
    '甲寅': 'Wood Tiger: Confident Growth & Natural Leadership',
    '乙卯': 'Wood Rabbit: Gentle Expansion & Creative Flourish',
    '丙辰': 'Fire Dragon: Charismatic Vision & Powerful Presence',
    '丁巳': 'Fire Snake: Hidden Fire & Illuminating Wisdom',
    '戊午': 'Earth Horse: Confident Stability & Enduring Passion',
    '己未': 'Earth Goat: Nurturing Stability & Gentle Care',
    '庚申': 'Metal Monkey: Sharp Wit & Skillful Execution',
    '辛酉': 'Metal Rooster: Polished Perfection & Valuable Assets',
    '壬戌': 'Water Dog: Deep Trust & Protective Flow',
    '癸亥': 'Water Pig: Deep Connections & Peaceful Flow',
  };
}
